### PR TITLE
Fix stdin pipe is being closed exception on Windows for large .proto files

### LINKED ISSUE #2147: Running check/apply with buf on Windows fails for files slightly over 4100 bytes
## Summary

`spotlessProtobufCheck/Apply` fails with pipe has closed exception, when processing .proto files larger than 4100 bytes, only on Windows.
Reducing the size of the .proto file (remove the last message on attached project) results in successful task execution.

## Environment

Spotless: 6.25.0
Buf: 1.31.0
Gradle: 8.7
JVM: Oracle/GraalVM/Temurin 21
OS:  OS: Windows 10 Pro Build: 22H2 (19045)
Shell: PowerShell 7.4.2

## Stacktrace

English translation for "パイプは終了しました" is "The pipe is being closed".

```
#### buf: C:\Users\valkyrie\.gradle\caches\modules-2\files-2.1\build.buf\buf\1.31.0\4152371536f12671d4f04b3c2aa14c3182dd1774\buf-1.31.0-windows-x86_64.exe
> Task :spotlessInternalRegisterDependencies UP-TO-DATE

> Task :spotlessProtobuf FAILED
Step 'buf' found problem in 'src\main\proto\service.proto':
パイプは終了しました。
java.io.IOException: パイプは終了しました。
	at com.diffplug.spotless.ProcessRunner.start(ProcessRunner.java:166)
	at com.diffplug.spotless.ProcessRunner.start(ProcessRunner.java:131)
	at com.diffplug.spotless.ProcessRunner.exec(ProcessRunner.java:114)
	at com.diffplug.spotless.ProcessRunner.exec(ProcessRunner.java:109)
	at com.diffplug.spotless.protobuf.BufStep$State.format(BufStep.java:93)
	at com.diffplug.spotless.FormatterFunc$Closeable$3.apply(FormatterFunc.java:125)
	at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:82)
	at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:103)
	at com.diffplug.spotless.Formatter.compute(Formatter.java:246)
	at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:203)
	at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:190)
	at com.diffplug.gradle.spotless.SpotlessTaskImpl.processInputFile(SpotlessTaskImpl.java:105)
	at com.diffplug.gradle.spotless.SpotlessTaskImpl.performAction(SpotlessTaskImpl.java:89)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:45)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.execute(IncrementalTaskAction.java:26)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
	at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:244)
```

Attached is the full stacktrace for `./gradlew spotlessProtobufCheck --stacktrace`.
[stacktrace.txt](https://github.com/diffplug/spotless/files/15490766/stacktrace.txt)

## Reproducible project

Attached is a minimal gradle project that can reproduce the problem. Just run `./gradlew build` or `./gradlew spotlessProtobufCheck` to reproduce the problem. buf executable is automatically provisioned on the build script for convenience, but running with defaults (using buf executable available on `PATH`) results with same exception.
[spotless-buf-sample.zip](https://github.com/diffplug/spotless/files/15490668/spotless-buf-sample.zip)

---

If you are submitting a **bug**, please include the following:

- [x] summary of problem
- [x] Gradle or Maven version
- [x] spotless version
- [x] operating system and version
- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [x] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

If you're just submitting a feature request or question, no need for the above.

### PR DESCRIPTION
**Pull request by azam**
## Summary

This fixes #2147.

`ProcessRunner` closes the stdin stream on execution which throws an `IOException` with `Pipe is being closed` message on Windows for protobuf files slightly larger than 4100 bytes. This fix removes the `OutputStream#close()` call on `ProcessRunner`, but this should not affect current behavior, since the file descriptor and stream for stdin will be closed when the process is destroyed ([unix](https://github.com/openjdk/jdk/blob/a7864af08acbe63d09f770ca66780738260faac4/src/java.base/unix/classes/java/lang/ProcessImpl.java#L478),[windows](https://github.com/openjdk/jdk/blob/a7864af08acbe63d09f770ca66780738260faac4/src/java.base/windows/classes/java/lang/ProcessImpl.java#L516)).

Also added a test with a dirty `.proto` file that is slightly over 4100 bytes.

----
Please **DO NOT FORCE PUSH**. Don't worry about messy history, it's easier to do code review if we can tell what happened after the review, and force pushing breaks that.

Please make sure that your [PR allows edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).  Sometimes it's faster for us to just fix something than it is to describe how to fix it.

Allow edits from maintainers

After creating the PR, please add a commit that adds a bullet-point under the `[Unreleased]` section of [CHANGES.md](https://github.com/diffplug/spotless/blob/main/CHANGES.md), [plugin-gradle/CHANGES.md](https://github.com/diffplug/spotless/blob/main/plugin-gradle/CHANGES.md), and [plugin-maven/CHANGES.md](https://github.com/diffplug/spotless/blob/main/plugin-maven/CHANGES.md) which includes:

- [x] a summary of the change
- either
    - [x] a link to the issue you are resolving (for small changes)
    - [ ] a link to the PR you just created (for big changes likely to have discussion)

If your change only affects a build plugin, and not the lib, then you only need to update the `plugin-foo/CHANGES.md` for that plugin.

If your change affects lib in an end-user-visible way (fixing a bug, updating a version) then you need to update `CHANGES.md` for both the lib and all build plugins.  Users of a build plugin shouldn't have to refer to lib to see changes that affect them.

This makes it easier for the maintainers to quickly release your changes :)

### CODE REVIEW

**Comment by nedtwigg** [comment]
I killed CI after 36 minutes, usually the tests complete in ~15 minutes.

Try running `./gradlew build` locally. I'm seeing that `BiomeStep` and `NativeCmdStep` are hanging as a result of the original change. I just pushed up a PR which calls a `flush` instead of `close`, we'll see how it does.

**Comment by nedtwigg** [comment]
Stopped tests after 20 minutes this time.

**Comment by nedtwigg** [comment]
Seems that the `close()` is important. Maybe just calling `flush()` before the `close()` will solve your issue. Good thing you added a test, and good thing we run our tests on Windows! https://stackoverflow.com/a/56013102/24181017

**Comment by azam** [comment]
Nice find! My bad that I should have run the full test suite 😅
Thank you for your time working on this issue.

**Pull request merged**
