### PR TITLE
google-java-format Windows bug workaround now only runs for affected version (1.1).

### PR DESCRIPTION
**Pull request by jbduncan**

### CODE REVIEW

**Comment by jbduncan** [comment]
Related to https://github.com/diffplug/spotless/issues/65.

**Comment by nedtwigg** [comment]
LGTM!

**Comment by nedtwigg** [comment]
Oh, except I didn't realize that it didn't bump the default version to `1.2`.  I think it should definitely use `1.2`.

**Comment by jbduncan** [comment]
> Oh, except I didn't realize that it didn't bump the default version to 1.2. I think it should definitely use 1.2.

Okey dokey! I've pushed a new commit fixing this at https://github.com/diffplug/spotless/pull/73/commits/1250f5ac6128cca47702e3128c0f76a337ab52c5.

**Comment by jbduncan** [comment]
Notes for self:
1. Update RemoveUnusedImports.java to use google-java-format 1.2.
2. Find a way to test that `fixWindowsBug` is only run if google-java-format version is 1.1. @nedtwigg Do you have any thoughts on how I could do this?

**Comment by nedtwigg** [comment]
1. I think that's already done: https://github.com/diffplug/spotless/blob/25004228013b8f583bd6d821d6232f37fc2a240d/lib/src/main/java/com/diffplug/spotless/java/RemoveUnusedImportsStep.java#L30
2. Perfect world would have a test, I don't see a good way to do it.  I think we should merge, and then test 3.1.0-SNAPSHOT on junit.  If removeUnusedImports now works for them, that's good enough for me.  Feel free to merge at your convenience / satisfaction :)

**Comment by jbduncan** [comment]
1. Oh yes, you're right! Thanks for pointing that out for me.
2. Okay, in that case I agree on merging this as-is. Doing that now. :)

**Comment by jbduncan** [comment]
@nedtwigg, how do you prefer PRs to be merged in for Spotless:

1. Merge commit,
2. Squash and merge commit,
3. Rebase and commit on top of master?

**Comment by nedtwigg** [comment]
Merge commit.  Easy to revert if there's a problem, keeps history intact.

**Comment by jbduncan** [comment]
Done. :)

**Comment by jbduncan** [comment]
Hi @nedtwigg, I've just tested the latest spotless-plugin-gradle snapshot against JUnit 5 snapshot with the `removeUnusedImports()` option enabled.

AFAICT, it works beautifully! So we should consider releasing 3.1 soon. :)

**Pull request merged**
