### PR TITLE
Add missing bracket in CHANGES.md

### PR DESCRIPTION
**Pull request by AntsyLich**

### CODE REVIEW

**Comment by AntsyLich** [comment]
@nedtwigg off topic but did build fail for maven and lib? They don't seem to have been updated. For reference: https://central.sonatype.com/namespace/com.diffplug.spotless

**Comment by nedtwigg** [comment]
Publish succeeded, but it might not be propagated to maven central yet. That used to be instantaneous, but has become pretty slow recently.

**Comment by AntsyLich** [comment]
I see. Will wait for few more hours then.

**Comment by AntsyLich** [comment]
Speak of the devil they appear now.

**Pull request merged**
