### PR TITLE
eclipse-base and eclipse-wtp refactoring

### PR DESCRIPTION
**Pull request by fvgh**
This PR provides a refactoring of eclipse-base configuration aiming to make the configuration more readable and thread save.
Further more the configuration provides support for Eclipse bundles without activator, as for example required by [org.eclipse.core.filesystem 1.7.600](https://bugs.eclipse.org/bugs/show_bug.cgi?id=550548).

The eclipse-base changes are applied on WTP. Furthermore WTP has been refactored to disallow multiple instantiations with different configurations. The previous approach was not thread save as reported in #492 

For demonstration purpose, the new eclipse-base configuration has been applied on all other eclipse formatters as well.

Note that for building `eclipse-base` sub-project has to be published first.
As result of this PR the new versions of `eclipse-base` and `eclipse-wtp` shall be published on maven central.

### CODE REVIEW

**Comment by fvgh** [comment]
@nedtwigg 
I applied `spotless-changelog`, please have a last look at 8e2c7c7968383ce42cbea0ea992f4665b1774a4c.
Not sure when you update the log (on branch or master).
Feel free to merge and publish (eclipse-base and eclipse-wtp) in which order (publish/merge) you prefer.
As soon as the new versions are available, I'll provide an update for lib-extra, fixing #492.

**Comment by nedtwigg** [comment]
Sorry it took me so long, and sorry I broke the build for a bit in the middle.  Publishing logic is always a little tricky to test :)

**Comment by nedtwigg** [comment]
Just FYI, I merged this history into master, so that the published tags are ancestors of master.

**Comment by fvgh** [comment]
@nedtwigg I see the point. But in this case it would be better next time to merge accepted changes first and than do the publishing, wouldn't it?

**Comment by nedtwigg** [comment]
I think you are correct, and I will do it that way from now on.

Now that we have adopted `spotless-changelog`, it will be possible for us to cut a release using [CircleCI triggers](https://circleci.com/docs/2.0/triggers/).  I haven't used it before, but I think there would be a committer-only dashboard, and you could push the "release eclipse-base" button, and it would calculate the version, publish to mavenCentral, bump the changelog, tag, and push.  It's a nice blend between automatic and manual.

Not sure when I'll have a chance to work on the CircleCI thing, but that is the motivation behind the churn I introduced with spotless-changelog.

**Comment by fvgh** [comment]
Interesting. Like to see it running.

**Comment by nedtwigg** [comment]
Released in `x.28.0`

**Pull request merged**
