### PR TITLE
Groovy-Eclipse  3.0.0

### PR DESCRIPTION
**Pull request by fvgh**
Upgrade of Spotless Eclipse Groovy formatter to Groovy 2.6 / Groovy-Eclipse 3.0.0 as requested in #237.

### CODE REVIEW

**Comment by fvgh** [comment]
@boris-petrov Think it will be part of next release...

**Comment by nedtwigg** [comment]
You have been busy @fvgh!  Tons of great stuff from you in this release!  Is there any work that you've done that's waiting on me to publish something from `_ext`?  I think I need to publish `_ext/eclipse-groovy`, can you confirm?  Also is `_ext/eclipse-cdt` also waiting on me?

**Comment by fvgh** [comment]
Maybe I should have been more explicit @nedtwigg . Yes, I need new versions for eclipse-cdt (9.4.4) and eclipse-groovy (3.0.0). I prepared already the corresponding integration branches.

**Comment by nedtwigg** [comment]
Published eclipse-groovy 3.0.0 and eclipse-cdt 9.4.4.  To make sure I don't hold you up in the future, let's setup the following protocol in the future: send me an email (it's in my profile) with subject line "publish eclipse-groovy 3.0.0".  That'll move them to the top of my queue, and make sure I don't hold you up, and that I publish the correct version.

**Pull request merged**
