### PR TITLE
feat: support pass skip from command-line for maven-plugin

### PR DESCRIPTION
**Pull request by tisonkun**
cc @nedtwigg 

If this is acceptable, I'm glad to add a changelog entry if necessary.

### CODE REVIEW

**Comment by nedtwigg** [comment]
Looks good to me! Add a changelog under `### Added` and I'll be happy to merge.

**Comment by tisonkun** [comment]
@nedtwigg Thank you! I'll update this today.

BTW, can diffplug be an alternative to GitHub Desktop? I'm trying to use a Git client app to overcome some network issues and practice your advice in our first collaboration that I missed to push a local commit.

I encounter this issue on GitHub Desktop and try to find an alternative - I don't know if this is the right place to ask this question, but I don't find other channels.

**Comment by tisonkun** [comment]
Changelog updated.

**Comment by nedtwigg** [comment]
>  can diffplug be an alternative to GitHub Desktop

That's exactly what it is! It's free too :). If you have more questions about it I would use: https://discuss.diffplug.com/top?period=all

**Pull request merged**
