### PR TITLE
Provision of Spotless Eclipse CDT formatter plugin.

### PR DESCRIPTION
**Pull request by fvgh**

### CODE REVIEW

**Comment by nedtwigg** [comment]
Fantastic!  Like #230, I'm happy to merge now, and then work on UI and docs in a new PR if you prefer.

**Comment by fvgh** [comment]
@nedtwigg Please don't provide a release now. I will make some updates, integrating the eclipse-mock (I prefer the name eclipse-base) as discussed for #230 .

**Comment by nedtwigg** [comment]
`cdt` and `wtp` are both published to mavencentral.  Might take a few hours before they're available from mavencentral, but they're definitely available from jcenter right now.  Just FYI, had to make a small change to the `cdt` pom to get mavencentral to accept it: https://github.com/diffplug/spotless/commit/f6bca4d7d486e6bf91bc195892102f9ee81aaf11

**Comment by nedtwigg** [comment]
Btw, I played around with `spotless-eclipse-base` in a little test project the other day - great API, works really well.  We should publicize this more with a blog post / tweet.  If you have a blog we can publish there and tweet it, else I'm happy to write a post and publish from mine.  I'm slammed at the moment, but hopefully can get to this in a month or so.

**Comment by fvgh** [comment]
I am always happy if my work is useful for other people.Feel free to promote it. 

Sorry for the missing Maven compliant fix for CDT. I did it for the others, but somehow forgot to align the CDT build properties.

**Pull request merged**
