### PR TITLE
Upgrade Cleanthat. Enable draft

### PR DESCRIPTION
**Pull request by blacelle**
Upgrade Cleanthat to ~2.3~ ~2.4~ 2.6

Enable includeDraft option

### CODE REVIEW

**Comment by nedtwigg** [comment]
Thanks! I'll merge and release by Friday.

**Comment by blacelle** [comment]
@nedtwigg This is at your own discretion, but I would strongly suggest merging PR (at least external PR (at the very least the PR from myself)) through squash-commits. I do not make much efforts to have a clean commits history within a PR as I hope for squashing to whole thing into the main branch. (Github has options to default/enforce the PR-merging policy)

**Comment by nedtwigg** [comment]
Thanks, noted. I like to have access to the thought process that went into merged commits, but I agree the GitHub commits view doesn't make that easy. Fwiw `git log --first-parent` looks good :)

**Comment by nedtwigg** [comment]
Published in `plugin-gradle 6.16.0` and `plugin-maven 2.34.0`.

**Pull request merged**
