### PR TITLE
Added Eclipse 4.21 support.

### PR DESCRIPTION
**Pull request by fvgh**
Please have a quick look at the CHANGES.md, since I am no native speaker.

### CODE REVIEW

**Comment by nedtwigg** [comment]
>  I am no native speaker.

Wow! FWIW we've worked together for a quite a few years now and I would never have guessed that you weren't a native speaker.

(Also I don't care if our docs etc. have english-as-a-second-language spelling errors or unusual idioms as long as the result is readable, but it's really impressive to learn a second language all the way to native fluency in writing, and imo you made it!)

**Comment by marcphilipp** [comment]
@nedtwigg Do you have an idea when this will be released? I'm hoping it might improve the formatting of sealed classes which is currently very awkward. Case in point: https://github.com/junit-team/junit5/pull/2728/files#diff-1b923dba2a8d4bea6d45efd817e204083a8ae86cb7d80f70b796b4182a8694f2

**Comment by nedtwigg** [comment]
Sorry, we're jammed up atm. I'll post to this issue when a release can finally happen again.

https://github.com/diffplug/spotless/issues/950

**Comment by nedtwigg** [comment]
Published in `plugin-gradle 5.15.2` and `plugin-maven 2.14.0`.

**Pull request merged**
