### PR TITLE
Drop old KtLint support(0.3x and 0.45.2)

### PR DESCRIPTION
**Pull request by eirnym**
Drop old versions of KtLint (0.3x and 0.45.2)

### CODE REVIEW

**Comment by nedtwigg** [comment]
Also: just a heads up that this PR is also not getting run on CircleCI. It must be something about @eirnym's permissions, other recent PR's are building on Circle.

It's not worth digging into, #1472 will fix this for good, and I can run tests manually by pushing to a new branch myself. Just leaving this note so I don't forget to do that before merging.

**Comment by eirnym** [comment]
@nedtwigg Please, have a look on #1477 which adds minimal-enough CI builds.

**Comment by davidburstrom** [comment]
It makes sense to drop some, it's always possible to reinstate from Git. I would rather think in terms of time than number of versions, e.g. keep support for all versions released in the last year. Ultimately it's in the interest of the consumers of Spotless that they can keep up with the KtLint versions with sufficient reaction time.

**Comment by nedtwigg** [comment]
> I would rather think in terms of time than number of versions

In a world where `ktlint` could provide a stable API, we could support a decade into the past without any trouble. My only gripe is the maintenance burden, which is proportional to number of versions. How about a policy of:

- we will always maintain at least the last 365 days' worth of ktlint
- we will never maintain more than 3 incompatible versions (so 2 breaking changes)

**Comment by jbduncan** [comment]
Hey @nedtwigg, out of these two conditions:

> - we will always maintain at least the last 365 days' worth of ktlint
> - we will never maintain more than 3 incompatible versions (so 2 breaking changes)

...which would you prefer to take priority if they ever clash?

**Comment by nedtwigg** [comment]
Lol, excellent point!

- we will always *try* to maintain the last 365 days' worth of ktlint
- but we will not maintain more than 3 incompatible versions at once
- so if ktlint breaks their API more than twice in a year, we will not be able to support a full year's worth of releases
- and if ktlint can maintain a stable API for more than a year, we may choose to drop down to only a single implementation

**Comment by nedtwigg** [comment]
@davidburstrom is this policy okay with you?

**Review by Goooler — APPROVED** [review]

**Comment by eirnym** [comment]
@nedtwigg now every test passes

**Comment by nedtwigg** [comment]
Released in `plugin-gradle 6.14.0` and `plugin-maven 2.31.0`.

**Pull request merged**
