### PR TITLE
Implement Gherkin formatting plugin

### LINKED ISSUE #907: Implement Gherkin formatting plugin
Something that @goughy000 mentioned recently is that having the ability for Spotless to format our Gherkin files for Cucumber testing would be super useful.

Between the two of us we're looking at getting this implemented for Gradle.

<details>
<summary>Working thoughts</summary>

https://github.com/cucumber/cucumber-jvm/blob/main/gherkin-messages/src/main/java/io/cucumber/core/gherkin/messages/GherkinMessagesFeatureParser.java
https://github.com/JetBrains/intellij-plugins/tree/master/cucumber/src/org/jetbrains/plugins/cucumber
https://github.com/cucumber/cucumber-eclipse/blob/main/cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/PrettyFormatter.java
https://github.com/podnov/gherkin/tree/main/utils/src/main/java/com/evanzeimet/gherkin/formatter

</details>

### PR DESCRIPTION
**Pull request by jamietanna**
Closes #907.

### CODE REVIEW

**Comment by nedtwigg** [comment]
Very cool, thx for opening, looks like you're on the right track, lmk when you'd like more input / ready to merge.

**Comment by jamietanna** [comment]
Thanks @nedtwigg - should be ready for reviews when you get a chance.

(I'll need to rebuild the PR shortly - I've just pushed the dependent upstream library, but it takes ~15-20 minutes to appear in Maven Central)

**Comment by jamietanna** [comment]
Moving to a draft because there's a change that I'd prefer to be in the upstream library before this should be widely usable

**Comment by nedtwigg** [comment]
Just FYI, if you'd like to remove the reflection code, you could use the approach in https://github.com/diffplug/spotless/pull/1012 if you'd like. Happy to merge either way.

**Comment by nedtwigg** [comment]
Superceded by #1649

**Comment by nedtwigg** [comment]
Published in `plugin-gradle 6.18.0` and `plugin-maven 2.36.0`.

**Pull request closed without merging**
