### PR TITLE
Provision of Spotless Eclipse XML formatter plugin.

### PR DESCRIPTION
**Pull request by fvgh**
XML formatter plugin based on Eclipse WTP-WST for #140.

### CODE REVIEW

**Comment by fvgh** [comment]
The positive aspects are:
*  [Configurability](https://github.com/diffplug/spotless/pull/230/files#diff-c6f9be119fc9c073020b1bb11aa3825bR165)
*  [DTD restrictions](https://github.com/diffplug/spotless/pull/230/files#diff-26cafab8bd78ddfa60a4e9c51271328bR4)
*  [XSD facets](https://github.com/diffplug/spotless/pull/230/files#diff-0e35126ec6a3c6d5ff8728ce0d51ae16R9)
*  [Catalog support](https://github.com/diffplug/spotless/pull/230/files#diff-5529271eee2412cb00710c3d9cdf11c6R127) for DTD/XSD lookup


On the downside, we would need an [interface extension](#diff-92b14eeb150b5b37e4f0e5e8bbcb8b54R52), since the XSD/DTD location might be relative to the file which shall be formatted.
The approach uses currently a fat JAR, which takes 5.4 MB. I would like to stick to the solution for now and refactor it as part of #226.


Please have a look whether you can agree first of all to the [interface extension](#diff-92b14eeb150b5b37e4f0e5e8bbcb8b54R52). In that case I can continue to work on a proposal for `lib-extra`

**Comment by fvgh** [comment]
The normal interface is:
`public String format(String raw)`
XML needs the following, since it needs to know the file path it is modifying for XSD/DTD/XInclude lookup:
`public String format(String raw, String baseLocation)`

This violates the simple/efficient concept of Spotless formatters where you just build up a chain of String processors.
Sure that you can agree to the extension?

Possible work-around would be to analyze all XML files first and generate an "internal catalog", but that's quite error prone...

Before merge, we should discuss whether I should instead of providing a XML formatter plugin, I should provide a WDT plugin, that supports also JS/HTML formatting. I made a corresponding proposal for #162 .

**Comment by fvgh** [comment]
Glad to here that it has not that much code impact.

About the "up-to-data" check:
Yes, as you can see in the examples, the DTD/XSD configures the XML format. This is explicitly foreseen by the W3C and had originally been introduced for XLST, but is also respected by WDT formatter.
You are right about the up-to-date check, but wrong about it's correspondence to the "internal catalog".
It is quite common that XSDs for example include other XSDs and furthermore not all of them need to be part of the work-space (can be referenced by http, but also be within JARs). Only possibility to detect all involved external documents, is an analysis of the WDT/CM document cache after initial run. But since WDT just ignores XSD/DTD/..., which it cannot resolve, that result might be erroneous.


To conclude:
I would not add any up-to-data checks. The user should know about the `--rerun-tasks` if he/she does fancy things.

As stated in previous comment, the provision of a WDT plugin instead of the XML plugin might be useful for the further development of spotless. Any thoughts on this one?

**Comment by nedtwigg** [comment]
Sounds good.  If we just do `implements FormatterStep` then the param you want will be there, and it won't do any up-to-date checking.

Re: WDT, if you want to use WDT, then I want to add it.  If you're only adding WDT in case other people might want it, then I think we should leave it out.  It's easy to build things, but it's hard to be sure that they're useful unless you're actually using them on real projects with real people.

**Comment by fvgh** [comment]
WDT I use, but I only use Core/XML/XSD/XSD.
It also provides HTML, which requires JS and all modules mentioned above.
So if I include HTML (and therefore JS), this solution would provide a solution for  #162 and #140.
Unfortunately I found that solving #191 would need some of the extensions I provided here. Do you see the possibility to split the Eclipse Mocking off the WDT and make it a separate lib on Maven Central?

**Comment by nedtwigg** [comment]
I think there's probably a pretty good hunk of demand for your eclipse mocking as its own library!  Happy for it to live and publish from _ext for however long you would like, but I bet it could find new users of its own for other applications as `fvgh/eclipsemock` too :)

**Comment by fvgh** [comment]
The branch will be split into eclipse-base (containing Spotless OSIG bundle controller and Eclipse services) and eclipse-wdt (extension of current eclipse-xml also supporting WDT formatter for JS and HTML).

**Pull request closed without merging**
