### PR TITLE
Switch from Travis to CircleCI

### PR DESCRIPTION
**Pull request by nedtwigg**

### CODE REVIEW

**Comment by nedtwigg** [comment]
On Travis, we were seeing build times of ~10-20 mins for each commit.  On CircleCI, running the same tests, we're seeing ~3 mins.  The real advantage, though, is that now any committer can ship a new version from the CI dashboard.

**Comment by jbduncan** [comment]
Fantastic work! 👏

Did you ever consider GitHub Actions at some point? I suppose I'm curious to know if Actions is slower than CircleCI or something. :)

**Comment by jbduncan** [comment]
I'm also curious to know more about this CircleCI dashboard. Is it open to external contributors, by any chance?

**Comment by nedtwigg** [comment]
> Did you ever consider GitHub Actions at some point?

I have only glanced at Actions.  I use CircleCI on other projects and I've been very happy with it, so it's been on my todo list to transfer this off of Travis for a while.

If Actions is way better than Circle I'm still open to adopting it, but in general I try to buy/advertise services from more independent vendors rather than platform-monopolists when I can (even if the platform-monopolist is behaving admirably today, which they are).

>  Is it open to external contributors, by any chance?

I hope so - that is my intent.  If you click the commit status for any commit on `master` (the only branch where the deploy pipeline runs), then hopefully you should see screens like this:

Screen Shot 2020-05-05 at 2 49 31 AM

The "on hold" jobs allow a committer to approve them, which will then ship `lib`, `plugin-gradle`, and `plugin-maven`, or just one of the plugins.

**Comment by jbduncan** [comment]
Hi @nedtwigg, sorry for the delay in responding, busy week!

> I have only glanced at Actions. I use CircleCI on other projects and I've been very happy with it, so it's been on my todo list to transfer this off of Travis for a while.
> 
> If Actions is way better than Circle I'm still open to adopting it, but in general I try to buy/advertise services from more independent vendors rather than platform-monopolists when I can (even if the platform-monopolist is behaving admirably today, which they are).

Sounds very reasonable to me! Speed and relative independence sound like great pluses to have. :+1: 

> If you click the commit status for any commit on master (the only branch where the deploy pipeline runs), then hopefully you should see screens like this...

Awesome, I can confirm that I have access! (I wasn't able to see the commit statuses before because I was viewing GitHub on my phone.)

**Comment by JLLeitschuh** [comment]
> is that now any committer can ship a new version from the CI dashboard.

Isn't that a security risk?

**Comment by nedtwigg** [comment]
Some projects automatically cut a release for every commit to master.  This is just that, except the release only happens if a committer tells CI “release this one” from the dashboard.

**Pull request merged**
