### PR TITLE
Reinstate support for KtLint down to 0.31.0 and up to 0.47.1 (inclusive)

### PR DESCRIPTION
**Pull request by davidburstrom**
Fixes https://github.com/diffplug/spotless/issues/1281

### CODE REVIEW

**Comment by davidburstrom** [comment]
I recommend reviewing this commit by commit. Let me know if I've missed something, this is the first time I'm contributing to Spotless.

**Review by eirnym — APPROVED** [review]

**Comment by eirnym** [comment]
Nice work! I'd love it to be merged soon!

**Comment by davidburstrom** [comment]
Yeah, I'd love to merge it but I need to have workflows approved first :)

**Comment by davidburstrom** [comment]
I verified that KtLint 0.47.1 also works.

**Comment by eirnym** [comment]
@davidburstrom Could you please run `spotlessApply` to make sure build passes?

**Comment by davidburstrom** [comment]
@eirnym Done! Thanks for pointing it out.

**Comment by nedtwigg** [comment]
Thanks for a great PR, sorry for slow merge. This will be released by tomorrow AM.

**Comment by nedtwigg** [comment]
Released in `plugin-gradle 6.11.0` and `plugin-maven 2.26.0`.

**Pull request merged**
