### PR TITLE
Sort by keys inside json arrays

### PR DESCRIPTION
**Pull request by genuss**
Hi team!
I'd like to propose an improvement of JSON formatting feature implemented in https://github.com/diffplug/spotless/pull/1125
Now, if `sortByKeys` is enabled, objects are recursively sorted but arrays are skipped. Take a look at this JSON for example:
```json
{
  "array": [
    {
      "b": "b",
      "a": "a"
    }
  ]
}
```
Note that keys are not sorted now and will not be sorted after applying the formatter. My proposal is to sort these keys too.
I'm not sure whether existing configuration property should be reused as this changes the behaviour of GSON formatter. If it's not acceptable I can add another property like `sortByKeysInArrays` to preserve backwards compatibility. When we choose which one is better, I'll certainly add some tests.
Let me know, what do you think about it.

### CODE REVIEW

**Comment by nedtwigg** [comment]
I think the behavior you have implemented is the correct behavior, and the old behavior was a bug. Labelling it as "potentially breaking" is perfect, alerts people who may have come to rely on the bug.

If anyone wants to add a flag in the future "sortByKeysExceptArrayElements" to restore the previous behavior, I would merge that PR so that they could keep the old behavior.

To get merged, this PR needs

- entries in plugin-gradle/CHANGES and plugin-maven/CHANGES
- a test https://github.com/diffplug/spotless/blob/main/testlib/src/test/java/com/diffplug/spotless/json/gson/GsonStepTest.java

**Comment by genuss** [comment]
Thanks for comments, a key to restore the old behaviour is even better! Will do everything tomorrow and send an update.

**Comment by genuss** [comment]
All done. As we consider this as a bug, I didn't add a new test but modified the existing one.

**Comment by nedtwigg** [comment]
Tests are failing. Looks like the plugin integration tests don't like the changes.

**Comment by genuss** [comment]
Indeed I didn't ran integration tests. Fixed and reran everything locally, it should pass now.

**Comment by nedtwigg** [comment]
Implemented in `plugin-gradle 6.14.1` and `plugin-maven 2.32.0`.

**Pull request merged**
