### PR TITLE
Fix external p2ant proxy configuration and added documentation.

### PR DESCRIPTION
**Pull request by fvgh**
Fixes build error for Eclipse formatters using fat-JARs.

### CODE REVIEW

**Comment by fvgh** [comment]
@nedtwigg I use an interceptive middle proxy. Since you are the author of **p2asmaven** :

1. Is there any generic way to modify p2ant directly from the init.gradle, without my script extension?
2. Do you know whether the Eclipse Ant tasks allow me to disable mirrors (since leads to many misses)?

**Comment by nedtwigg** [comment]
> 1. Is there any generic way to modify p2ant directly from the init.gradle, without my script extension?

I don't think so.

> 2. Do you know whether the Eclipse Ant tasks allow me to disable mirrors?

I don't know much about the eclipse ant tasks.

**Comment by fvgh** [comment]
Thanks for the clarification and sorry for the inconvenience when trying to publish the Eclipse formatters...

**Comment by nedtwigg** [comment]
No worries! `wtp` and `cdt` are uploaded, waiting on bintray for approval.

**Pull request merged**
