### PR TITLE
RDF Formatter Contribution

### PR DESCRIPTION
**Pull request by fkleedorfer**
Adds a formatter for RDF

In its current form, only the TTL format can be formatted using [turtle-formatter](https://github.com/atextor/turtle-formatter). All other formats could be handled with Jena, but are currently not implemented.

The PR contains code for a maven plugin, but not a gradle/sbt plugin.

Options are: 
- failOnWarnings: fail if the Jena parser warns
- verify: after formatting, parse both input and formatted output to a jena Model and compares them. If they are not isomorphic, outputs an error message
- turtle: a list of style options for the turtle-formatter as documented in the [turtle-formatter README](https://github.com/atextor/turtle-formatter?tab=readme-ov-file#customizing-the-style) Not all options are supported, though.

The PR includes smoke tests that use input/output folders containing files with identical names, for which a utility method was added to the ResourceHarness.

### CODE REVIEW

**Comment by fkleedorfer** [comment]
FYI: Expecting a dependency update for turtle-formatter soon-ish ([PR](https://github.com/atextor/turtle-formatter/pull/31) already submitted). If it is allowed by your review process, I'd bump that dependency as it becomes available.

**Comment by nedtwigg** [comment]
Looks great! Needs an entry in the `plugin-maven/README.md` docs and it's good to merge (assuming CI passes)

**Comment by fkleedorfer** [comment]
I think it's done now.

**Comment by fkleedorfer** [comment]
@nedtwigg ... what do I do? rebase and force-push ?

**Comment by nedtwigg** [comment]
Run `./gradlew spotbugsMain` and I think it'll show you the problem.

**Comment by fkleedorfer** [comment]
Done.

**Comment by fkleedorfer** [comment]
Limited the tests to JDK >= 17 to deal with the tests failing for java 11. Hope that's it now.

**Comment by fkleedorfer** [comment]
@nedtwigg could you please approve the workflow runs? Thanks!

**Comment by nedtwigg** [comment]
Released in `plugin-gradle 7.0.0.BETA3` and `plugin-maven 2.44.0.BETA3`.

**Pull request merged**
