### PR TITLE
Update jgit

### PR DESCRIPTION
**Pull request by wreulicke**
Update jgit

- [x] a summary of the change
- either
    - [ ] a link to the issue you are resolving (for small changes)
    - [x] a link to the PR you just created (for big changes likely to have discussion)

## Note

~The branch of this PR is based on #408.~
rebased

### CODE REVIEW

**Comment by nedtwigg** [comment]
Is there a particular reason for the version bump?  I've been hoping for https://git.eclipse.org/r/#/c/126454/ to land so that we can fix #75, but the change keeps getting buried in whitespace controversy.

**Comment by wreulicke** [comment]
@nedtwigg
> Is there a particular reason for the version bump?

jgit has dependency to httpcomponents.
It is so old version, so other gradle plugin that has dependency of httpcomponents is broken in the project with spotless on gradle.

**Comment by nedtwigg** [comment]
Great!  Can you add something to that effect in the changelog?!  For [lib](../blob/master/CHANGES.md), [plugin-gradle](../blob/master/plugin-gradle/CHANGES.md), and [plugin-maven](../blob/master/plugin-maven/CHANGES.md).

**Comment by wreulicke** [comment]
> Great! Can you add something to that effect in the changelog? For [lib](../blob/master/CHANGES.md), [plugin-gradle](../blob/master/plugin-gradle/CHANGES.md), and [plugin-maven](../blob/master/plugin-maven/CHANGES.md).

I will

**Comment by wreulicke** [comment]
@nedtwigg 
added.

**Comment by wreulicke** [comment]
@nedtwigg
Could you review again?

**Comment by nedtwigg** [comment]
Thanks @wreulicke.  I'm hoping we can get #328 into this release too.  I'll publish on Monday either way.

**Comment by wreulicke** [comment]
thanks a lot

**Comment by nedtwigg** [comment]
Released in `x.23.1`

**Comment by wreulicke** [comment]
Congratulations! Thanks!
I will try it!

**Comment by basil** [comment]
FYI, this upgrade caused a hang for me when running Spotless, but only on NFS:

```
"Execution worker for ':' Thread 3" #31 prio=5 os_prio=0 tid=0x00007f87f25c3000 nid=0xbe8 waiting on condition [0x00007f872baf6000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at org.eclipse.jgit.util.FS$FileStoreAttributeCache.<init>(FS.java:240)
	at org.eclipse.jgit.util.FS$FileStoreAttributeCache.getFsTimestampResolution(FS.java:211)
	at org.eclipse.jgit.util.FS.getFsTimerResolution(FS.java:321)
	at org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>(FileSnapshot.java:186)
	at org.eclipse.jgit.internal.storage.file.FileSnapshot.save(FileSnapshot.java:122)
	at org.eclipse.jgit.storage.file.FileBasedConfig.load(FileBasedConfig.java:155)
	at com.diffplug.spotless.extra.GitAttributesLineEndings$FileState$$Lambda$109/391424876.run(Unknown Source)
	at com.diffplug.common.base.Errors.lambda$wrap$5(Errors.java:218)
	at com.diffplug.common.base.Errors$$Lambda$107/1270883703.run(Unknown Source)
	at com.diffplug.common.base.Errors.run(Errors.java:210)
	at com.diffplug.spotless.extra.GitAttributesLineEndings$FileState.<init>(GitAttributesLineEndings.java:180)
	at com.diffplug.spotless.extra.GitAttributesLineEndings$Policy.calculateState(GitAttributesLineEndings.java:92)
	at com.diffplug.spotless.extra.GitAttributesLineEndings$Policy.calculateState(GitAttributesLineEndings.java:79)
	at com.diffplug.spotless.LazyForwardingEquality.state(LazyForwardingEquality.java:56)
	- locked <0x00000000c1f6d918> (a com.diffplug.spotless.extra.GitAttributesLineEndings$Policy)
	at com.diffplug.spotless.LazyForwardingEquality.writeObject(LazyForwardingEquality.java:68)
[...]
```

I looked into it further and tracked the issue down to eclipse/jgit@b513b7747713a505e19e237ac2e7f8d9c699bc4d. When I downgraded to jgit 5.3.1.201904271842-r (which doesn't have that commit), the problem went away:

```
buildscript {
  configurations.classpath {
    resolutionStrategy {
      force 'org.eclipse.jgit:org.eclipse.jgit:5.3.1.201904271842-r'
    }
  }
}
```

**Comment by nedtwigg** [comment]
Thanks for letting us know, especially the workaround.  I assume that `5.4.0` won't help either, since it's only a few days newer than `5.3.2`.  Do you know if there's an existing bug in the jgit tracker for this?

**Comment by basil** [comment]
jgit bug [548188](https://bugs.eclipse.org/bugs/show_bug.cgi?id=548188) has a reference to [what appears to be a fix](https://git.eclipse.org/r/144605) checked in on July 4. I haven't been able to determine if that fix has been released yet.

**Comment by nedtwigg** [comment]
The very latest release was June 14, so it hasn't been released yet.  We have another outstanding bug related to this jgit update in #410.  Its fix was merged into jgit on July 17th.  So I believe that both this and that will be resolved at the same time when the next jgit comes out.

**Comment by nedtwigg** [comment]
Updated to latest again in `3.24.3`

**Pull request merged**
