### PR TITLE
Support ktlint `0.50.0` and drop support for `0.47.0`

### PR DESCRIPTION
**Pull request by magneticflux-**
Closes https://github.com/diffplug/spotless/issues/1741

Please **DO NOT FORCE PUSH**. Don't worry about messy history, it's easier to do code review if we can tell what happened after the review, and force pushing breaks that.

Please make sure that your [PR allows edits from maintainers](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/).  Sometimes its faster for us to just fix something than it is to describe how to fix it.

Allow edits from maintainers

After creating the PR, please add a commit that adds a bullet-point under the `[Unreleased]` section of [CHANGES.md](https://github.com/diffplug/spotless/blob/main/CHANGES.md), [plugin-gradle/CHANGES.md](https://github.com/diffplug/spotless/blob/main/plugin-gradle/CHANGES.md), and [plugin-maven/CHANGES.md](https://github.com/diffplug/spotless/blob/main/plugin-maven/CHANGES.md) which includes:

- [x] a summary of the change
- either
    - [x] a link to the issue you are resolving (for small changes)
    - [ ] a link to the PR you just created (for big changes likely to have discussion)

If your change only affects a build plugin, and not the lib, then you only need to update the `plugin-foo/CHANGES.md` for that plugin.

If your change affects lib in an end-user-visible way (fixing a bug, updating a version) then you need to update `CHANGES.md` for both the lib and all build plugins.  Users of a build plugin shouldn't have to refer to lib to see changes that affect them.

This makes it easier for the maintainers to quickly release your changes :)

---

Additional notes for discussion:

- KtLint 0.50.0 introduces a new default rule `wrapping` that changes the formatting of `resources/kotlin/ktlint/basic.dirty`. I created `basic-old.clean` for KtLint < 0.50.0 and changed `basic.clean` to wrap the semicolon-separated lines.
- `KtLintCompat0Dot50Dot0Adapter` constructs a `KtLintRuleEngine` with the default value of `true` for `enableKotlinCompilerExtensionPoint`. We may want this to be user-configurable to help people debug their custom rule providers. More info here: https://github.com/pinterest/ktlint/issues/1981
- `EditorConfigDefaults.Companion.load` supports adding custom property types to parse from the `.editorconfig`, in addition to the defaults. Another potential location for user-configuration.

### CODE REVIEW

**Comment by magneticflux-** [comment]
An additional note:
Since this drops support for KtLint 0.47.0, all supported releases of KtLint use `ktlint_experimental` instead of a special parameter ([0.48.0 changelog](https://github.com/pinterest/ktlint/releases/tag/0.48.0)). Should we drop the `boolean useExperimental` parameter from `KtLintCompatAdapter` and rely solely on the `ktlint_experimental` property?

**Comment by nedtwigg** [comment]
Sorry for the slow review, this is great!

> Should we drop the boolean useExperimental parameter from KtLintCompatAdapter and rely solely on ktlint_experimental? This would clean up some warning code in each compat adapter:

That would be fantastic, thanks! I'll merge and release as soon as that is complete.

**Comment by magneticflux-** [comment]
Expected impact of the removal of `useExperimental` is minimal.
- [~105 usages with](https://github.com/search?q=%22ktlint%28%22+AND+%22useExperimental%22+AND+path%3A%22build.gradle%22&type=code)
- [~5100 usages without](https://github.com/search?q=%22ktlint%28%22+AND+%28NOT+%22useExperimental%22%29+AND+path%3A%22build.gradle%22&type=code)

**Comment by magneticflux-** [comment]
The NPM `eslintStyleguideXo()` test failure seems unrelated.
```
Error: ROR] Step 'eslint-format' found problem in 'src/main/typescript/test.ts':
  > Unexpected response status code at /eslint/format [HTTP 500] -- (Error while formatting: Error: --config#overrides[0] » eslint-config-xo-typescript:
  > 	Configuration for rule "@typescript-eslint/no-restricted-imports" is invalid:
  > 	Value ["error","domain","freelist","smalloc","punycode","sys","querystring","colors"] should be string.
  > 	Value ["error","domain","freelist","smalloc","punycode","sys","querystring","colors"] should be object.
  > 	Value ["error","domain","freelist","smalloc","punycode","sys","querystring","colors"] should match some schema in anyOf.
  > 	Value ["error","domain","freelist","smalloc","punycode","sys","querystring","colors"] should be object.
  > 	Value [["error","domain","freelist","smalloc","punycode","sys","querystring","colors"]] should match some schema in anyOf.
  > )
  > com.diffplug.spotless.npm.SimpleRestClient$SimpleRestResponseException: Unexpected response status code at /eslint/format [HTTP 500] -- (Error while formatting: Error: --config#overrides[0] » eslint-config-xo-typescript:
  > 	Configuration for rule "@typescript-eslint/no-restricted-imports" is invalid:
  > 	Value ["error","domain","freelist","smalloc","punycode","sys","querystring","colors"] should be string.
  > 	Value ["error","domain","freelist","smalloc","punycode","sys","querystring","colors"] should be object.
  > 	Value ["error","domain","freelist","smalloc","punycode","sys","querystring","colors"] should match some schema in anyOf.
  > 	Value ["error","domain","freelist","smalloc","punycode","sys","querystring","colors"] should be object.
  > 	Value [["error","domain","freelist","smalloc","punycode","sys","querystring","colors"]] should match some schema in anyOf.
  > )
```

**Comment by nedtwigg** [comment]
Released in `plugin-gradle 6.20.0` and `plugin-maven 2.38.0`.

**Pull request merged**
