### PR TITLE
Allow multiple calls to `target` or `targetExclude`

### PR DESCRIPTION
**Pull request by RinOrz**
Fixed https://github.com/diffplug/spotless/issues/939 in a way that would not destroy any API of the **spotless**.

### CODE REVIEW

**Comment by nedtwigg** [comment]
Imagine this scenario:

```gradle
// root build.gradle
allprojects {
  spotless {
    java { target 'src/main/**/*.java' ...
// sub/build.gradle
spotless {
  java { target 'src/test/**/*.java' ...
```

Before this PR, the target in `sub/build.gradle` would be `src/test/**/*.java`, but after this PR, it would be `[src/main/**/*.java, src/test/**/*.java]`. Importantly, the target in the `sub` project depends on stuff that happens outside the project - there is global mutable state, and calling `target` in the subproject can't wipe that out. That is why #939 is closed as won't implement, and this PR doesn't address that problem.

Can you describe why your usecase can't be resolved with the existing API?

**Comment by RinOrz** [comment]
> but after this PR, it would be `[src/main/**/*.java, src/test/**/*.java]`. 

Yes, this is what I expect, I hope the subproject will not overwrite the previously defined `target` and `targetExclude`, because I wrote a Gradle preset plugin, which uses `allprojects` to preset some `targetExclude`, however, in a specific project, I want to add an exclusion target, which is a special use case. Therefore, in that issue, I mentioned `addTarget`, which is a method that will not destroy the current behavior.

**Comment by RinOrz** [comment]
This PR occurs because I am currently unable to implement this behavior through external methods ( 😢

**Comment by nedtwigg** [comment]
Would you be okay with `target(getTarget(), 'src/test/**/*.java')`? If so, I'm okay with adding `getTarget()` and `getTargetExclude()` methods, which could allow you to explicitly append to the existing target.

**Comment by RinOrz** [comment]
> Would you be okay with `target(getTarget(), 'src/test/**/*.java')`?

Good idea!

**Comment by nedtwigg** [comment]
If you still need this, feel free to open a new PR with the `getTarget()` and `getTargetExclude()` methods.

**Pull request closed without merging**
