### PR TITLE
Spotless Eclipse Framework Final

### PR DESCRIPTION
**Pull request by fvgh**
Changes for final version 3.0.0 (Commits on Jul 14, 2018) were not considered by #234.

### CODE REVIEW

**Comment by fvgh** [comment]
@nedtwigg As I already mentioned in #234, I was missing some changes. Just rechecked, they did not went into the PR. I have no clue why.

**Comment by fvgh** [comment]
@nedtwigg Had a final test of the conflicts solved manually within this PR. The branch is in line with my local one. So I am ready to merge.

**Comment by nedtwigg** [comment]
Hmm, I tried to publish, but I'm getting a build error:

```
cmd> ./gradlew -b _ext/eclipse-base/build.gradle jar
/Users/ntwigg/Documents/dev/spotless/_ext/eclipse-base/src/main/java/com/diffplug/spotless/extra/eclipse/base/osgi/ServiceCollection.java:99: error: ServiceCollection.FrameworkServiceReference is not abstract and does not override abstract method getProperties() in ServiceReference
        private class FrameworkServiceReference<S> implements ServiceReference<S> {
                ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/ntwigg/Documents/dev/spotless/_ext/eclipse-base/src/main/java/com/diffplug/spotless/extra/eclipse/base/osgi/BundleConfig.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
```

I'll push my config up as a PR.

**Comment by nedtwigg** [comment]
Oh, sorry, I think I realized my misunderstanding.  This branch needs to be merged first?  And then I publish `spotless-eclipse-base`?  If that is the case, press merge, and tell me when to publish :)

**Comment by nedtwigg** [comment]
Ahh yes, sorry, just catching up on the thread.  I see that you've prepped this branch for publishing (like you said, the PR's are being presented in a weird way).  I'm merging this and publishing!

**Comment by fvgh** [comment]
@nedtwigg Thanks!

**Comment by nedtwigg** [comment]
Okay!  The package is published to bintray: https://bintray.com/diffplug/opensource/spotless-eclipse-base

I asked bintray to publish this to jcenter, which requires manual approval from them.  Once they've approved it, I'll be able to sync to mavencentral, and we'll have a publishing pipeline for this.  I'm headed to bed, but I expect we'll get approved sometime tomorrow.

Great work @fvgh, very excited to have this land to users soon :)

**Comment by nedtwigg** [comment]
Now available in jcenter and mavencentral as `com.diffplug.spotless:spotless-eclipse-base:3.0.0`.

**Comment by fvgh** [comment]
@nedtwigg Thanks for adding the sources o the publication. Just remembered it after I saw your notification that you published :smile: Thought that I have to live without sources fro this version. 

Feel free to continue with JDT/Groovy.

**Comment by nedtwigg** [comment]
Great!

- eclipse-jdt:4.8.0 is published to https://bintray.com/diffplug/opensource/spotless-eclipse-jdt, waiting for jcenter/mavencentral approval.
- eclipse-groovy:2.9.2 is published to https://bintray.com/diffplug/opensource/spotless-eclipse-groovy, waiting for jcenter/mavencentral approval

Just FYI, I got some warnings/errors in compiling eclipse-groovy:

```
p2AsMaven p2 is dirty.
Initalizing maven group p2 from p2
Only needs to be done once, future builds will be much faster
p2AsMaven p2 installing from p2
Buildfile: /var/folders/ht/lym17q3x5l11ctrwgh2_n6d40000gn/T/goomph-ant-build8998017386257088880.xml
[p2.mirror] Problems resolving provisioning plan.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy 1.8.9.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.runtime 0.0
.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy25.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.apache.ant 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy25.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy25.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.junit 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy 2.0.8.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy 2.1.9.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy 2.2.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy 2.3.11.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.jface 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.text 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.jface.text 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.ui.editors 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.jdt.ui 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.ui 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.debug.core 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.debug.ui 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.jdt.debug 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.jdt.launching 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.jdt.debug.ui 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.ui.views 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.core.filebuffers 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.ui.console 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.jdt.junit 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.apache.ant 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.junit 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.ui.workbench 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.ui.navigator 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.ui.ide [3.2.0,4.0.0).
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.ui.workbench.texteditor [3.2.0,4.0.0).
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.core.expressions [3.2.0,4.0.0).
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.core.resources [3.2.0,4.0.0).
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.compare [3.2.0,4.0.0).
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.core.variables [3.1.0,4.0.0).
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.jdt.junit4.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE toorg.eclipse.jdt.junit.runtime [3.2.0,4.0.0).
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy 2.4.13.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.astviews 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.astviews 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.astviews 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.resources 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.astviews 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui.editors 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.astviews 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui.workbench.texteditor 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.astviews 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.jface.text 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy 2.5.0.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.refactoring 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.expressions 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.refactoring 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.resources 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.refactoring 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.refactoring 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.jdt.core.manipulation 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.refactoring 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.jdt.ui 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.refactoring 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.jface 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.refactoring 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.jface.text 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.refactoring 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ltk.core.refactoring 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.refactoring 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ltk.ui.refactoring 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.refactoring 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.refactoring 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui.editors 3.5.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.refactoring 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui.workbench.texteditor 3.5.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy22.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.apache.ant 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy22.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.junit 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy22.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.dsl 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.filesystem 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.dsl 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.resources 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.dsl 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.dsl 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.dsl 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui.ide 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy24.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.apache.ant 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy24.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy24.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.junit 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.codebrowsing 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.resources 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.codebrowsing 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ant 2.9.2.xx-201801041714-e47-RELEASE to bundle org.apache.ant 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ant 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ant.core 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy23.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.apache.ant 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy23.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.junit 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy23.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.m2eclipse 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.resources 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.m2eclipse 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.m2eclipse 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.m2e.jdt 1.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.m2eclipse 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.m2e.core 1.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.m2eclipse 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.m2e.maven.runtime 1.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.m2eclipse 2.9.2.xx-201801041714-e47-RELEASE to package org.eclipse.ui.preferences 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.quickfix 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.resources 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.quickfix 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.quickfix 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.jface.text 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.quickfix 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ltk.core.refactoring 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.quickfix 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.quickfix 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui.editors 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.quickfix 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui.workbench.texteditor 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.expressions 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.filesystem 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.variables 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.debug.ui 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.jdt.core.manipulation 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.jdt.debug 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.jdt.debug.ui 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.jdt.junit 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.jdt.launching 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.jdt.ui 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.jface.text 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ltk.core.refactoring 3.5.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ltk.ui.refactoring 3.4.100.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.search 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui.browser 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui.console 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui.editors 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui.ide 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui.views 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.ui 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui.workbench.texteditor 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.codeassist.completion 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.resources 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.codeassist.completion 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.codeassist.completion 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.jdt.ui 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.codeassist.completion 2.9.2.xx-201801041714-e47-RELEASE to bundl
e org.eclipse.jface 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.codeassist.completion 2.9.2.xx-201801041714-e47-RELEASE to bundl
e org.eclipse.jface.text 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.codeassist.completion 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.codeassist.completion 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui.editors 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.codeassist.completion 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.ui.workbench.texteditor 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy20.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.apache.ant 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy20.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.junit 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy20.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.compilerResolver 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.eclipse.jdt.core 3.13.100.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.resources [3.12.0,4.0.0).
[p2.mirror] Unable to satisfy dependency from org.eclipse.jdt.core 3.13.100.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.runtime [3.13.0,4.0.0).
[p2.mirror] Unable to satisfy dependency from org.eclipse.jdt.core 3.13.100.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.filesystem [1.7.0,2.0.0).
[p2.mirror] Unable to satisfy dependency from org.eclipse.jdt.core 3.13.100.xx-201801041714-e47-RELEASE to bundle org.eclipse.text [3.6.0,4.0.0).
[p2.mirror] Unable to satisfy dependency from org.eclipse.jdt.groovy.core 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.resources 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.eclipse.jdt.groovy.core 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.eclipse.jdt.groovy.core 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.text 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy21.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.apache.ant 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy21.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.junit 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy21.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy18.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.apache.ant 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy18.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.junit 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy18.feature.feature.group 2.9.2.xx-201801041714-e47-RELEASE to org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.core 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.core.runtime 0.0.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.core 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.jdt.launching 3.5.0.
[p2.mirror] Unable to satisfy dependency from org.codehaus.groovy.eclipse.core 2.9.2.xx-201801041714-e47-RELEASE to bundle org.eclipse.osgi 0.0.0.
[p2.mirror] Messages while mirroring artifact descriptors.
BUILD SUCCESSFUL

BUILD SUCCESSFUL
Total time: 1 minute 2 seconds
p2AsMaven p2 creating maven repo
p2AsMaven p2 is complete.

Download https://repo.maven.apache.org/maven2/org/eclipse/platform/org.eclipse.jface.text/maven-metadata.xml
Download https://repo.maven.apache.org/maven2/org/eclipse/platform/org.eclipse.jface.text/3.13.0/org.eclipse.jface.text-3.13.0.pom
Download https://jcenter.bintray.com/org/eclipse/platform/org.eclipse.jface.text/maven-metadata.xml
Download https://repo.maven.apache.org/maven2/org/eclipse/platform/org.eclipse.jface/maven-metadata.xml
Download https://jcenter.bintray.com/org/eclipse/platform/org.eclipse.jface/maven-metadata.xml
Download https://repo.maven.apache.org/maven2/org/eclipse/platform/org.eclipse.jface.text/3.13.0/org.eclipse.jface.text-3.13.0.jar
Download https://repo.maven.apache.org/maven2/org/eclipse/platform/org.eclipse.jface/3.14.0/org.eclipse.jface-3.14.0.jar
```

**Comment by nedtwigg** [comment]
`com.diffplug.spotless:spotless-eclipse-jdt:4.8.0` and `com.diffplug.spotless:spotless-eclipse-groovy:2.9.2` are now both available on mavencentral.

**Comment by fvgh** [comment]
@nedtwigg  About the errors/warnings: I hat the problem already in #13 . As [we discussed](https://github.com/diffplug/spotless/issues/13#issuecomment-284544053), I have not really an idea how P2 works. This time it additionally complains about dependencies provided already by `spotless-eclipse-base`. But I think the latter one is more a `p2.asmaven` issue. I can have a further look if you want. `p2.asmaven` basically brought me in touch with Eclipse development, but I gathered till now just some insight into Eclipse framework and did not look at P2. As you wrote in your article:

> it (P2) can be daunting for newcomers to use.

:smiley:

**Comment by nedtwigg** [comment]
I only wanted to bring it up in case the version I published had a different set of warnings than you expected.  I don't anticipate any problems, but if you encounter any surprises while closing this out, it might be a place to look.

**Pull request merged**
