### PR TITLE
Use modern API to get property values

### PR DESCRIPTION
**Pull request by Goooler**
https://docs.gradle.org/8.5/userguide/build_environment.html#configuring_your_build_environment

### CODE REVIEW

**Comment by Goooler** [comment]
Some of these APIs are introduced in Gradle 6.2, we probably should merge this after bumping the min requirement.

**Comment by jbduncan** [comment]
Nice! LGTM. It makes sense to me to wait until we depend on Gradle 6.2.

**Comment by nedtwigg** [comment]
Awesome, thanks @Goooler! Want to bump the minimum Gradle in this PR? That will get it to pass tests, and then we can merge. `6.2` is very old, I'm fine to bump our requirements to that (or newer if needed)

- https://github.com/diffplug/spotless/blob/13d962769ee8adeaf7cac31aad7f01c1f0f2ee77/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessPlugin.java#L29
- https://github.com/diffplug/spotless/blob/main/plugin-gradle/src/test/java/com/diffplug/gradle/spotless/GradleIntegrationHarness.java
- docs

**Comment by Goooler** [comment]
That would be a breaking change, I'm not sure if we should do it in minor releases. Might be in the next major update.

**Comment by nedtwigg** [comment]
Thanks for being so cautious!

**Comment by nedtwigg** [comment]
Gradle on Java 11 is failing with

```
com.diffplug.gradle.spotless.GitRatchetGradleTest > singleProjectExhaustive(int) [1] 0 FAILED (16.1s)

  org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in /tmp/junit4180957295393577931 with arguments [spotlessCheck]
  
  Output:
  
  FAILURE: Build failed with an exception.
  
  * Where:
  Build file '/tmp/junit4180957295393577931/build.gradle' line: 2
  
  * What went wrong:
  An exception occurred applying plugin request [id: 'com.diffplug.spotless']
  > Failed to apply plugin 'com.diffplug.spotless'.
     > Cannot obtain value from provider of Gradle property 'spotlessModern' at configuration time.
       Use a provider returned by 'forUseAtConfigurationTime()' instead.
```

**Comment by nedtwigg** [comment]
- Also need to update https://github.com/diffplug/spotless/tree/main/plugin-gradle#requirements

**Comment by nedtwigg** [comment]
If bumping to `6.3` or `6.4` or whatever fixes the issue, we should just do that.

**Comment by Goooler** [comment]
Some tests failed due to without `forUseAtConfigurationTime` using, we need something like 
```kt
private fun <T> Provider<T>.forUseAtConfigurationTimeCompat(): Provider<T> =
  if (GradleVersion.current() < GradleVersion.version("6.5")) {
      // Gradle < 6.5 doesn't have this function.
      this
  } else if (GradleVersion.current() < GradleVersion.version("7.4")) {
      // Gradle 6.5 - 7.3 requires this function to be called.
      @Suppress("DEPRECATION")
      this.forUseAtConfigurationTime()
  } else {
      // Gradle >= 7.4 deprecated this function in favor of not calling it (became no-op, and will eventually nag).
      // https://docs.gradle.org/current/userguide/upgrading_version_7.html#for_use_at_configuration_time_deprecation
      this
  }
```
to compact various Gradle versions, I would hold this after before min Gradle requirement to 7.4

**Comment by nedtwigg** [comment]
Do we get anything positive by switching to these APIs? is it related to project isolation (#1979)?

If we don't get anything useful, it might be worth dealing with the annoyance. Seems like there's only 4 `.get`s and and 6 `.isPresent` by my count.

**Comment by Goooler** [comment]
It would be a suggestion for migration from Gradle side, but every property getting works well with CC, I believe we have no much emergency to do it for now.

**Comment by nedtwigg** [comment]
Roger, thanks for looking into this!

**Pull request closed without merging**
