### PR TITLE
Support KtLint 0.34+

### LINKED ISSUE #419: ktLint 0.34 changes not compatible with spotless
Last version of ktLint 0.34 seems to have changes that are not compatible with spotless.

```
Execution failed for task ':utils:spotlessKotlin'.
> java.lang.NoSuchMethodException: com.pinterest.ktlint.core.KtLint.format(java.lang.String, java.lang.Iterable, java.util.Map, kotlin.jvm.functions.Function2)
```

### PR DESCRIPTION
**Pull request by ZacSweers**
This resolves #419 by invoking the new `format(Params)` API in KtLint 0.34+. This API also lays groundwork for adding editorconfig in the future since the new `Params` API allows specifying one. Opportunistically also fixed some stale names in 3812713.

Starting this now for early review, will add a test next.

### CODE REVIEW

**Comment by ZacSweers** [comment]
Reverting part of 3812713, realize why the naming was as such before now

**Comment by nedtwigg** [comment]
As you say - needs test, but looks great!

**Comment by ZacSweers** [comment]
Actually no new test needed. The default `behavior()` test covers this now, and the existing `worksPinterest()` test acts as a regression test for the old behavior on [0.32.0-0.34.0). Just clarified it in 9c5c264

**Comment by nedtwigg** [comment]
Updated the changelogs.  This LGTM.  I'll merge and release late tonight / early tomorrow unless I hear otherwise from somebody.

**Comment by ZacSweers** [comment]
Sounds good!

**Comment by ZacSweers** [comment]
Made just a couple touchups to the comments and trailing paren formatting. Comments weren't quite right before

**Comment by ZacSweers** [comment]
Spotless overwrote my paren formatting

**Comment by nedtwigg** [comment]
Released in `3.25.0`.

**Pull request merged**
