### PR TITLE
Don't treat `@Value` as a type annotation

### PR DESCRIPTION
**Pull request by mernst**
Related: https://github.com/typetools/checker-framework/pull/5364

### CODE REVIEW

**Comment by nedtwigg** [comment]
I'm okay with this, but we need to add it in all three changelogs like so:

```
[Unreleased]
### Fixed
* Some message (link to PR)
```

I'm not sure what the changelog message should be, I'm happy to merge anything.

**Comment by mernst** [comment]
Thanks for the feedback.  I wasn't sure whether the change merited a changelog entry.  I have now added them as you requested.

**Comment by nedtwigg** [comment]
Thanks for the PR! I could publish a release with only this change, but I have a slight preference to wait for a more substantial new feature or bugfix before creating the notification noise of a new release.

**Comment by mernst** [comment]
Either way is fine with me.  Thanks!

**Comment by nedtwigg** [comment]
Published in `plugin-gradle 6.12.0` and `plugin-maven 2.28.0`.

**Pull request merged**
