### PR TITLE
Apply eclipse-jdt-4.8.1(2nd attempt)

### PR DESCRIPTION
**Pull request by fvgh**
The new version fixes module-info formatting.

Fix in #960 was incomplete. Still the old interface version was used.

### CODE REVIEW

**Comment by fvgh** [comment]
@nedtwigg I am afraid [my trick was too neat](https://github.com/diffplug/spotless/pull/960#discussion_r725521440). Should not merge too late in the evening. What do we do? Shall I refactor history?

**Comment by fvgh** [comment]
Code will always use the function with one parameter, because its the only function I selected:
```java
Method method = formatterClazz.getMethod(FORMATTER_METHOD, String.class);
```
Test will always pass, since I still support the old interfaces.
2 parameters are only relevant for `module-info.java`. For the rest the formatter functionality has not changed.

Strictly speaking, I owe you an additional test. I should prepare the `module-info.java` test of `spotless-eclipse-jdt` so that I can reuse it in `lib-extra`.

I just dropped this fix quickly, so that you don't release with this incomplete fix.

**Comment by fvgh** [comment]
Sorry  @nedtwigg, you lost me.
We have a change log entry (Fixed...module-info formatting...) in 59819eba41e8a3fcccdca5438c45a620958c86ec.
The previous commit was only incomplete.
The commit  message should just be the same as the previous one.

The "Eclipse formatter can now handle module-info.java" we had in b2c5cd908a6f3be7235920e831cae832ab4d4a16.
Followed by "Publish..." 25178b265fc1341dc95e74345cba686a0f52ae50
So I thought, now we "Apply...".

**Comment by nedtwigg** [comment]
Works for me! Press merge whenever you're ready :)

**Pull request merged**
