### PR TITLE
fix: maven plugin should identify skip config key

### LINKED ISSUE #491: Maven plugin should support skip
Many maven plug-ins support skipping the plug-in altogether when skip is set to true in the configuration. In a big tree of modules, that can be useful for supporting setting up reasonable defaults, and then opting out in modules where this is not necessary. So, e.g.:

> 			<plugin>
>   				<groupId>com.diffplug.spotless</groupId>
>   				<artifactId>spotless-maven-plugin</artifactId>
>   				<configuration>
>     				<skip>true</skip>
>   				</configuration>
> 			</plugin>

### LINKED ISSUE #1227: Maven plugin skip no longer functional in 2.19.0 and above
The issue/enhancement: **Maven plugin should support skip #491** no longer functions as of release 2.19.0.
mvn spotless:check or mvn spotless:apply  does not get skipped as in earlier releases.
`            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>2.19.0</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
`

### PR DESCRIPTION
**Pull request by tisonkun**
* This closes #1227.
* This closes #491.

CHANGES updates will be pushed later. I trigger the CI tasks first.

### CODE REVIEW

**Comment by nedtwigg** [comment]
Thanks a lot @tisonkun! I'm ready to merge and release as soon as I get one "works for me" from someone.

**Comment by imaffe** [comment]
I'm trying to walk through the reproduce process.

**Comment by EricGao888** [comment]
> Thanks a lot @tisonkun! I'm ready to merge and release as soon as I get one "works for me" from someone.

@nedtwigg I have pulled this PR and tested the patch built from it locally. It works for me.

**Comment by syhily** [comment]
This PR works for me on my local machine.

**Comment by imaffe** [comment]
image

Has spot failure and have skip enabled, but not skipped on 2.26
image


After changing to local build 2.27.1-SNAPSHOT
image

And skipped: 
image

**Comment by nedtwigg** [comment]
Thanks very much to @tisonkun for the fix and everyone else for the testing confirmation! Released in `plugin-maven 2.27.1`. Should be available now, but mavenCentral has had some sync slowness recently, it'll get there within a few hours if it's not there already.

**Comment by bbarker-eb** [comment]
Thank you for this fix!

Regards,
Bonnie Barker

From: Ned Twigg ***@***.***>
Date: Wednesday, September 28, 2022 at 10:31 AM
To: diffplug/spotless ***@***.***>
Cc: Bonnie Barker ***@***.***>, Mention ***@***.***>
Subject: Re: [diffplug/spotless] fix: maven plugin should identify skip config key (PR #1353)

[EXTERNAL EMAIL]

Thanks very much to @tisonkun<https://urldefense.com/v3/__https:/github.com/tisonkun__;!!OtcDaF7ONWtCeTI!0E8kjODY3_0bYqVs9W5e35Vt30j1A99Xbf5sD-Q54E5NEZNzyxeGYsilYFEMaprL0Nc32FRrVEr2o86FrY4d1UVF15wJMIGy$> for the fix and everyone else for the testing confirmation! Released in plugin-maven 2.27.1. Should be available now, but mavenCentral has had some sync slowness recently, it'll get there within a few hours if it's not there already.

**Pull request merged**
