### PR TITLE
Update changelog for 3.2.0.

### PR DESCRIPTION
**Pull request by nedtwigg**

### CODE REVIEW

**Comment by jbduncan** [comment]
Oh, probably good to mention that `Formatter::compute` (will) no longer throw `Error`!

**Comment by nedtwigg** [comment]
`throw Error` has the same effect as `throw RuntimeException` - it doesn't actually mean anything.  It was a mistake to have written it.

**Comment by jbduncan** [comment]
Oh I see! Then still LGTM. :+1:

**Comment by nedtwigg** [comment]
Between Kotlin #92, ignore failures #79, and fixing strict errors in #96, we've got some valuable fixes that are waiting on Groovy.  Groovy's got a little way to go, so I'm inclined to merge #96 later today and ship the backlog.

**Pull request merged**
