### PR TITLE
Anounce the arrival of the IntelliJ plugin.

### PR DESCRIPTION
**Pull request by nedtwigg**
Thanks to @ragurney, we now have an 🎉🎉🎉 IntelliJ plugin 🎉🎉🎉 (#200)!

I advertised everywhere that the VSCode plugin was advertised, let me know if you find any other places.

For our existing VSCode plugin, there is:

- a marketplace link: https://marketplace.visualstudio.com/items?itemName=richardwillis.vscode-spotless-gradle
- and a github repo: https://github.com/badsyntax/vscode-spotless-gradle

We used the marketplace link as the canonical link for pointing users at. I'm inclined to do the same thing for this IntelliJ plugin, but for now all we have is a GitHub repo link while Ryan waits on JetBrains to approve his plugin

- https://github.com/ragurney/spotless-intellij-gradle

I think I'll leave this PR as a draft until JetBrains approves the plugin and we have a marketplace link, ala

- https://plugins.jetbrains.com/plugin/10874-git-bisect-run

### CODE REVIEW

**Comment by ragurney** [comment]
Hey @nedtwigg, I just got confirmation that the plugin has been approved and made generally available on the JetBrains plugin marketplace 🎉 

It can be accessed via this link: 
https://plugins.jetbrains.com/plugin/18321-spotless-gradle

**Comment by nedtwigg** [comment]
Huzzah! I'll hit merge when these two issues are fixed :)

- https://github.com/ragurney/spotless-intellij-gradle/issues/17
- https://github.com/ragurney/spotless-intellij-gradle/issues/18

**Comment by ragurney** [comment]
Thanks @nedtwigg for finding that issue and for the feedback! Both of those issues should be resolved in v1.0.3 pending review by JetBrains to have it released to the marketplace.

**Comment by ragurney** [comment]
Annnd it's live

**Pull request merged**
