### PR TITLE
Fix UnsatisfiedLinkError we've been seeing in nodejs formatters

### LINKED ISSUE #302: J2V8 native library not loaded, libj2v8_macosx_x86_64.dylib already loaded in another classloader
If you are submitting a **bug**, please include the following:

- [x] summary of problem

  - If you use one version of spotless (e.g. `3.15.0-SNAPSHOT`)
  - and you run a `spotlessApply` that uses an npm rule
  - then use a new version (e.g. `3.15.0`)
  - and you run a `spotlessApply` that uses an npm rule
  - then you'll get the stacktrace copy-pasted later in this bug.

The workaround is easy, just run `gradlew --stop` to kill the old daemon.  Better would be to catch the error and tell the user "You can fix this with 'gradlew --stop'".  Best would be to fix it.

Not a high priority issue. :)

- [x] gradle or maven version: `4.10.2`
- [x] spotless version: `3.15.0`
- [x] operating system and version: `macOS 10.13.6`
- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible

[Public repo is here.](https://github.com/mytakedotorg/mytakedotorg/pull/212/commits/4ebdbc68ccc3cfa67af9bb9b26e28f5d69a9497f)

```gradle
spotless {
	format 'scss', {
		target 'src/main/styles/**/*.scss'
		prettier().config(['parser': 'postcss'])
	}
	format 'typescript', {
		target 'src/main/scripts/**'
		prettier().config(['parser': 'typescript'])
	}
}
```

- [x] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

```
Caused by: java.lang.IllegalStateException: J2V8 native library not loaded
        at com.eclipsesource.v8.V8.checkNativeLibraryLoaded(V8.java:195)
        at com.eclipsesource.v8.V8.createV8Runtime(V8.java:149)
        at com.eclipsesource.v8.V8.createV8Runtime(V8.java:125)
        at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:58)
        at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:45)
        at com.diffplug.spotless.npm.Reflective.invokeStaticMethod(Reflective.java:56)
        at com.diffplug.spotless.npm.NodeJSWrapper.lambda$new$0(NodeJSWrapper.java:39)
        at com.diffplug.spotless.npm.ReflectiveObjectWrapper.<init>(ReflectiveObjectWrapper.java:34)
        at com.diffplug.spotless.npm.NodeJSWrapper.<init>(NodeJSWrapper.java:33)
        at com.diffplug.spotless.npm.NpmFormatterStepStateBase.nodeJSWrapper(NpmFormatterStepStateBase.java:95)
        at com.diffplug.spotless.npm.PrettierFormatterStep$State.createFormatterFunc(PrettierFormatterStep.java:68)
        at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:76)
        at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:76)
        at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
        at com.diffplug.spotless.Formatter.applyToAndReturnResultIfDirty(Formatter.java:192)
        at com.diffplug.gradle.spotless.SpotlessTask.applyAnyChanged(SpotlessTask.java:230)
        at com.diffplug.gradle.spotless.SpotlessTask.performAction(SpotlessTask.java:193)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons:
        no j2v8_macosx_x86_64 in java.library.path
        Native Library /Users/ntwigg/libj2v8_macosx_x86_64.dylib already loaded in another classloader

        at com.eclipsesource.v8.LibraryLoader.loadLibrary(LibraryLoader.java:75)
        at com.eclipsesource.v8.V8.load(V8.java:71)
        at com.eclipsesource.v8.V8.createV8Runtime(V8.java:145)
        ... 58 more
```

### PR DESCRIPTION
**Pull request by nedtwigg**
Fixes #302, and also keeps the J2V8 dll out of the userhome directory.

### CODE REVIEW

**Comment by nedtwigg** [comment]
@simschla I did some hacking to fix the UnsatisfiedLinkError, and also to keep the dll's out of the userhome.  In particular, we used to do

https://github.com/diffplug/spotless/blob/5244a7e9d8958785b159bd8420f67e8ba36a91a3/lib/src/main/java/com/diffplug/spotless/npm/NodeJSWrapper.java#L38-L40

which I removed in c5ae0fb.  I'm on a windows machine, and it was throwing console errors, and after I removed it everything still worked fine (unit tests passed, and it worked for my projects).  Did I make a mistake and I should have left it in?

**Comment by simschla** [comment]
@nedtwigg Thank you for that (not so simple) fix 👍  I wasn’t able to fix it in a way that it would not throw console errors. Your solution looks good to me! thank you!

**Comment by source-knights** [comment]
@nedtwigg  Nice one (even if I'm not a fan of that reflection based code, but I understand there no better solution right now).

Is this only for the gradle plugin?

**Comment by nedtwigg** [comment]
The bug only showed up if J2V8 was loaded by multiple classloaders within one JVM.  Spotless caches these classloaders (to allow JIT warmup), so the bug is only triggered if some other daemon loads Spotless more than once.  So if you don't use the build daemon, you would never see this bug in Gradle.  I don't know maven well, but I expect that this would not affect maven users, but maybe it does?  Regardless, it is in the master branch of maven, and will be in the next release.

**Comment by source-knights** [comment]
@nedtwigg  the directory where the J2V8 was installed is an issue in Maven plugin as well, also the "setFlags", "-color=false"

That's why I was asking if this is only for the gradle plugin? As only the gradle changes file was amended I guess this has no effect in Maven plugin?

Thx

**Comment by nedtwigg** [comment]
> As only the gradle changes file was amended

I believe the maven changes was also updated, with the J2V8 install change mentioned.  I didn't mention the setFlags thing, happy to take a PR to improve the changelog if there's anything missing or confusing :)

https://github.com/diffplug/spotless/pull/586/files#diff-dba632fdc53b52d0b261faf5130512c7

**Comment by source-knights** [comment]
@nedtwigg ah, seems I somehow missed that. But yes, now I see the maven part was changed as well. Good stuff 👍

**Comment by nedtwigg** [comment]
Fixed in `plugin-maven 1.31.2` and `plugin-gradle 4.1.0`.

**Pull request merged**
