### PR TITLE
Implemented max lines width changing support for Kotlin ktfmt formatter for Gradle plugin.

### PR DESCRIPTION
**Pull request by DDeg**

### CODE REVIEW

**Review by nedtwigg — CHANGES_REQUESTED** [review]
- [ ] Update `CHANGES.md` (not just `plugin-gradle/CHANGES.md`)

Once that is done I'm happy to merge this as-is, but this would probably be a lot easier with https://github.com/diffplug/spotless/issues/524. Do you want to refactor to that approach? If you want to add other ktfmt features in the future, it would probably be worth the refactor.

**Comment by DDeg** [comment]
Updated review with new approach with compileOnly dependency usage.

**Review by nedtwigg — APPROVED** [review]
Fantastic, thanks very much! Sorry for slow release.

**Comment by nedtwigg** [comment]
Published in `plugin-gradle 6.4.0` and `plugin-maven 2.22.0`.

**Pull request merged**
