### PR TITLE
Bumped to Groovy-Eclipse version 2.9.2 (corresponds to Eclipse 4.8.0).

### PR DESCRIPTION
**Pull request by fvgh**
Using Groovy-Eclipse version 2.9.2.
As requested, the version used by the user configuration is equal to the "corresponding" Eclipse version (4.8.0). Note that not every transitive dependency is equal to the one used by Eclipse 4.8.0, but this should not have an impact on the formatter behaviour.

### CODE REVIEW

**Comment by fvgh** [comment]
@nedtwigg Please have a look at the [transitive dependencies I omitted](https://github.com/diffplug/spotless/pull/264/files#diff-504b50da2d6d114b7326c8d84c5d37c5R15). Problem is that the current `Provisioner` only allows to get all dependencies, including the once excluded from the [Spotless formatter dependencies](https://github.com/diffplug/spotless/blob/master/_ext/eclipse-groovy/build.gradle#L85). For `spotless-eclipse-jdt`, this only leads to a download of [unnecessary JARs](https://github.com/diffplug/spotless/blob/master/_ext/eclipse-jdt/build.gradle#L14-L16), but for example for `spotless-eclipse-groovy` it is fatal, since it will try to download some Maven coordinates not available on M2, but which are platform dependent and can therefore not easily be provided in the fat JAR. 

I would like to have a dedicated PR, extending the `Provisioner` correspondingly.

**Comment by fvgh** [comment]
@nedtwigg Not sure whether you had a look at my previous comment. This is an issue and makes this PR somewhat in-stable, since it leaves two transitive dependency versions "free" (within their major version) rolling. As [I sated for 263](https://github.com/diffplug/spotless/issues/263#issuecomment-406665745), I would prefer it you can provide the required `Provisioner` changes (method or additional argument is needed, so that Provisioner does not resolve transitive dependencies), since it affects the core design.

**Comment by nedtwigg** [comment]
Apologies @fvgh, I'm hard-capped on time right now and I don't have time to dig in deeper.  My #1 priority is to never block somebody else's work just because I don't have time to review it, but initiating new work on the Provisioner isn't going to make the top of my todo list for weeks at least.

**Comment by fvgh** [comment]
I will provide a draft and you can adapt it to your design goals... But be aware that the current Groovy version might crash one day due to underlying transitive incompatibilities. The Java version should be alright.

**Pull request merged**
