### PR TITLE
Add shell script support via shfmt

### PR DESCRIPTION
**Pull request by tcrawford-figure**
This adds Gradle support for shfmt and addresses https://github.com/diffplug/spotless/issues/1567

### CODE REVIEW

**Comment by Goooler** [comment]
Can you add maven support as well?

**Comment by nedtwigg** [comment]
Thanks for the great PR! Maven support is very welcome, but you're under no obligation to [fill the matrix](https://github.com/diffplug/spotless/blob/main/README.md#why-are-there-empty-squares).

**Comment by nedtwigg** [comment]
Published in `plugin-maven 2.42.0` and `plugin-gradle 6.24.0`.

**Comment by simschla** [comment]
Love this feature, thanks @tcrawford-figure ❤️ 

Wouldn't we need to add these special tests (`gradlew testShfmt`) to the ci github workflow, @nedtwigg ?

**Comment by tcrawford-figure** [comment]
@simschla happy to hear that! Based on feedback from @nedtwigg in the maven PR https://github.com/diffplug/spotless/pull/1998#discussion_r1454632452, yes. Adding these special tests to the github workflow would probably be good. I haven't had time to look into doing that yet. If you have time to work on that, by all means, please add support. Otherwise, I may look into it sometime in the next week.

**Pull request merged**
