### PR TITLE
obsolete - Add support for linters

### LINKED ISSUE #287: Don't fail after first codestyle violation
I tried out spotless today for the first time on one of our Kotlin projects and thus used the ktlint plugin.

It seems to work quite well so far, however `spotlessCheck` always fails right after finding the first codestyle violation while `ktlint` (when directly run on the codebase) lists all violations in a neat list.

I also tried to apply various different ktlint reporters (like the checkstyle one), but the result always seems to be the same - failure after the first violation (and in this case also no checkstyle XML is generated).

Long story short: can I force spotless (or the ktlint plugin, if that's the culprit) to continue its checks after it found a violation so that I can see all violations at a glance (and if possible without that stacktrace which causes the need for a lot of scrolling to find the error)?

Config looks like this:

```groovy
spotless {
    kotlin {
        ktlint().userData(['android': 'true', 'color': 'true', 'reporter': 'checkstyle'])
        target '**/*.kt'
    }
}
```

Sample output:

```
./gradlew :app:spotlessCheck 

> Configure project :app 
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Task :app:spotlessKotlin FAILED
Step 'ktlint' found problem in 'app/src/main/java/my/app/package/repository/game/MatchItemMapper.kt':
Error on line: 27, column: 1
Exceeded max line length (100)
java.lang.AssertionError: Error on line: 27, column: 1
Exceeded max line length (100)
        at com.diffplug.spotless.kotlin.KtLintStep$State.lambda$createFormat$0(KtLintStep.java:114)
        at com.sun.proxy.$Proxy96.invoke(Unknown Source)
        at com.github.shyiko.ktlint.core.KtLint$format$2$1.invoke(KtLint.kt:354)
        at com.github.shyiko.ktlint.core.KtLint$format$2$1.invoke(KtLint.kt:36)
        at com.github.shyiko.ktlint.ruleset.standard.MaxLineLengthRule.visit(MaxLineLengthRule.kt:69)
        at com.github.shyiko.ktlint.core.KtLint$format$2.invoke(KtLint.kt:352)
        at com.github.shyiko.ktlint.core.KtLint$format$2.invoke(KtLint.kt:36)
        at com.github.shyiko.ktlint.core.KtLint$visitor$2$3.invoke(KtLint.kt:216)
        at com.github.shyiko.ktlint.core.KtLint$visitor$2$3.invoke(KtLint.kt:36)
        at com.github.shyiko.ktlint.core.KtLint.visit(KtLint.kt:489)
        at com.github.shyiko.ktlint.core.KtLint.visit(KtLint.kt:490)
        at com.github.shyiko.ktlint.core.KtLint.visit(KtLint.kt:490)
        at com.github.shyiko.ktlint.core.KtLint.visit(KtLint.kt:490)
        at com.github.shyiko.ktlint.core.KtLint.visit(KtLint.kt:490)
        at com.github.shyiko.ktlint.core.KtLint.access$visit(KtLint.kt:36)
        at com.github.shyiko.ktlint.core.KtLint$visitor$2.invoke(KtLint.kt:214)
        at com.github.shyiko.ktlint.core.KtLint$visitor$2.invoke(KtLint.kt:36)
        at com.github.shyiko.ktlint.core.KtLint.format(KtLint.kt:347)
        at com.github.shyiko.ktlint.core.KtLint.format(KtLint.kt:277)
        at com.diffplug.spotless.kotlin.KtLintStep$State.lambda$createFormat$1(KtLintStep.java:128)
        at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:78)
        at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:76)
        at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
        at com.diffplug.spotless.Formatter.isClean(Formatter.java:167)
        at com.diffplug.gradle.spotless.SpotlessTask.check(SpotlessTask.java:263)
        at com.diffplug.gradle.spotless.SpotlessTask.performAction(SpotlessTask.java:205)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:spotlessKotlin'.
> Error on line: 27, column: 1
  Exceeded max line length (100)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed
```

### PR DESCRIPTION
**Pull request by nedtwigg**
*This is just a proposal, open to other UIs / designs / implementations*

This PR adds a [`Lint`](https://github.com/diffplug/spotless/blob/e8e5df5781a4c6dda73ffbe0c1cbeb3c8d52d19c/lib/src/main/java/com/diffplug/spotless/Lint.java) pojo, as well as the new method `FormatterFunc::lint` with the following default implementation:

https://github.com/diffplug/spotless/blob/e8e5df5781a4c6dda73ffbe0c1cbeb3c8d52d19c/lib/src/main/java/com/diffplug/spotless/FormatterFunc.java#L41-L44

We now split formatting into two parts: the composable `String -> String` part and the non-composable `List<Lint>` part. Before this PR, the only [way to "lint" was to throw a single exception](https://github.com/diffplug/spotless/issues/719#issuecomment-710270652). In this PR, those exceptions are now caught and transformed into a lint https://github.com/diffplug/spotless/commit/7a1e72a4de196d6b7450119dc3ae2d637b83142e which has the following implications:

- `apply` always succeeds (it traps errors and continues, rather than bubbling them up to the user)
- `check` shows every exception to the user at once (with a best-guess line number from parsing the error message)
  - fixes #287
- steps are free to be a pure linter or a hybrid formatter/linter
  - the value-add from Spotless is
    - [git ratchet](https://github.com/diffplug/spotless/tree/main/plugin-gradle#ratchet) 
    - maven/gradle/sbt and up-to-date/build-cache/config-cache
    - unified `spotless:off/on` across formatters and linters (#719)
  - for now, the limitation from Spotless is that the linter must do source-only analysis
    - it's very possible to workaround this in the future
  - #1089
  - #143 
- we no longer have a `FormatExceptionPolicy`, just a `LintSuppressionPolicy` https://github.com/diffplug/spotless/commit/dd5165f2e62b8e8976ea9be57b94189620d6c013

### Gradle integration notes
There's an interesting subtlety here specific to the Gradle plugin, but it could also matter for maven if we go further with up-to-date checking. The `spotlessJava` task generates a folder of "clean" files for each file which is found to be unclean. Here (https://github.com/diffplug/spotless/commit/a25ededb7cd682872a6d00ad1080ee679a7b4625) we extend that to also have a folder of "lint" files for each file found to have non-zero lints . However, the lints will be different if the user calls `./gradlew spotlessCheck` or instead `./gradlew spotlessApply spotlessCheck`. The "clean" content will be the same, but the line numbers and content of the lints will depend on whether `apply` was called or not, `spotlessJava` can't know that ahead of time, so for now we just compute the lints twice (https://github.com/diffplug/spotless/commit/89339cdc624a2f2921685462af78da568d5acab9). That's not as expensive as it seems because we can skip the double-compute for clean files, which is almost-always almost-all files.

### Open questions
There might be other things to think about too, but these are what is on my mind:

- should `spotlessApply` fail if there are any lints?
  - before this PR we failed on the first "lint" / exception, after this PR `apply` always succeeds
  - I think our goal of "think about formatting less" means that we should sweep lints under the rug until `spotlessCheck` (we could make `applyFailsOnLint = true` available as an option)
- should we support "info/warning/error" levels?
  - I think the answer is no, because that's the job of the step
  - It should be `fooLint().level('info').confidence(70)`, so that each step can handle that
  - At the spotless level, it should just be "lint = failure", suppress with something like https://github.com/diffplug/spotless/commit/dd5165f2e62b8e8976ea9be57b94189620d6c013
```gradle
spotless {
    suppressLintForPath 'blah.txt'
    suppressLintForStep 'blah'
    suppressLintForCode 'SOME_CODE'
    suppressLintForMsgMatchesRegex 'blah'
    printSuppressedLintsToConsole = false
```

- should we export a "report" of some kind?
  - https://github.com/diffplug/spotless/issues/655
  - for now we just print IDE-parseable stuff to console and make no guarantees it won't change
  - if we make a format, it should definitely be [a reviewdog standard](https://github.com/reviewdog/reviewdog#input-format)
  - SARIF is an option too
    - reviewdog plans to support it but its too complex https://github.com/reviewdog/reviewdog/tree/master/proto/rdf#the-static-analysis-results-interchange-format-sarif
    - github supports part of the standard out of the box https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning
    - this can be used freely in lib-extra https://github.com/Contrast-Security-OSS/java-sarif

### Moving forward

It would be great to have some draft PRs based on this `feat/lint` branch that exercise the new `lint` method. I'm very confident that `FormatterStep` and `FormatterFunc` are stable. The uncertain part is what fields `Lint` will have, and that will be determined by a combination of:

- what do the linters have to give
- what do sarif and reviewdog want

This is a big change so it will happen slowly :)

### CODE REVIEW

**Comment by rougsig** [comment]
thx, will try to make detekt lint ckecks with thas PR

**Comment by rougsig** [comment]
### Open questions
- should `spotlessApply` fail if there are any lints?
  - I think we need to make it possible not to fail and fail. Behavior can be selected with flag like `failOnLint`. Also we need to not fail on first lint exception, it should gather all lint exception and print all at one time.
- should we support "info/warning/error" levels?
  - Lintershave different levels of lint rules. It can be great if spotless can follow the log level of lint rule.
- should we export a "report" of some kind?
  - Its cool feature. I think we need it. It should be created in another PR with another issue.

**Comment by nedtwigg** [comment]
How about `enum FailOnLint { CHECK, CHECK_AND_APPLY, NOFAIL }`

**Comment by rougsig** [comment]
Can be. Or:

May be different tasks can be the Best solution? Like spotlessLint spotlessFormat?

**Comment by nedtwigg** [comment]
Degrees of freedom are cost (more surface to maintain, more ways for things to go wrong). It's only worth the cost if you get some value out of it.

The magic of spotless imo is that `check` says why your build failed, and `apply` fixes that as much as possible, and there's exactly nothing else to say. This simplicity is why I think there should not be any new tasks, and also why I think that Spotless should have no concept of "error/warning/info" - that should be configured per-linter.

**Comment by rougsig** [comment]
What is the plan for this feature? Waiting for me with a detekt PR?

**Comment by nedtwigg** [comment]
I'm waiting until we have at least two `FormatterStep` which use this feature, preferably three. Anyone can contribute a step by opening a PR against this `feat/lint` branch.

**Comment by nedtwigg** [comment]
A good one to add: https://github.com/openrewrite/rewrite

**Comment by nedtwigg** [comment]
I have been convinced that this is totally worth doing. There are three reasons:

1) Surprisingly, it *simplifies* the existing functionality by making our error handling simpler
2) It simplifies integration with hybrid fixers/linters like KtLint
3) It opens up a new class of tool like Spotbugs

I'm not sure if reason 3 is a good idea or not, but reasons 1 and 2 alone make it worthwhile.

In terms of disruption to our stakeholders:
- **end users** -> no disruption at all
- **contributors to FormatterSteps** -> no change, new abilities if they want, only real problem is merge conflicts from #1443 which needs to happen whether we do lint or not
- **contributors to build plugins** -> a little bit of change
- **contributors to IDE plugins** -> potentially a fair bit of change

`spotless-lib` is currently on version `2.x`. I'm planning to roll this out in three stages:

- #1443
  - brings merge conflicts to basically every PR that touches any tests but needs to happen someday
  - only affects test, no change for end users or API
- #1096
  - `spotless-lib 3.x` causes zero change for end users
  -  almost zero change for FormatterStep contributors
  - a tiny bit of chang to build plugins 
- `spotless-lib 4.x` brings lint (this PR)

The existing PR's have all gone stale (a year old), so I'll be force-pushing new bite-sized pieces in the next days/weeks.

**Comment by nedtwigg** [comment]
Thanks! It'll probably be a week or two before it's ready :)

**Comment by jbduncan** [comment]
On the subject of OpenRewrite, I've actually used it a bit on a [small project](https://github.com/jbduncan/guava-graph-utils/) with some success. But IIRC it focuses purely on "solving" rather than "yelling", not to mention it already has a Gradle plugin, so it's not clear to me how Spotless linting would help. I don't suppose you can remember why you mentioned it now, do you?

But perhaps an advantage of incorporating OpenRewrite into Spotless would be the speed gained from Spotless's caching mechanism (at least on the Gradle side).

**Comment by blacelle** [comment]
> for now, the limitation from Spotless is that the linter must do source-only analysis

I did not dig into the PR, but maybe this limitation is slightly stricter for now: 'the linter must do source-only analysis, one a per-file basis'. i.e. I suspect the first iteration will not be able to receive a whole Set of source-files in a single batch.

> A good one to add: https://github.com/openrewrite/rewrite

OpenRewrite behave (much) better when called on a source-set, than on each individual files.

> But IIRC it focuses purely on "solving" rather than "yelling",

I agree. (I integrated it as an underlying engine of [CleanThat](https://github.com/solven-eu/cleanthat/blob/master/openrewrite/src/main/java/eu/solven/cleanthat/language/openrewrite/OpenrewriteFormattersFactory.java), which is focused on _solving_ than _yelling_)

> enum FailOnLint { CHECK, CHECK_AND_APPLY, NOFAIL }

About `CHECK_AND_APPLY`, I feel people are more interested in a APPLY_AND_CHECK (i.e. try fixing, and please yell is there is still outstanding issues).

**Comment by ztlr** [comment]
Is this PR still relevant for a future release although it was labeled as "pr-archive"?
We are highly interested in this since it will fix https://github.com/diffplug/spotless/issues/287.

**Comment by nedtwigg** [comment]
This PR is absolutely still relevant to a future release, but it will be a while.

**Comment by nedtwigg** [comment]
@WillHolbrook which linter would you like to use? Merging this is blocked on me, but I could use help testing the API with specific steps that need the linter.

**Comment by nedtwigg** [comment]
Replaced by #2149

**Pull request closed without merging**
