### PR TITLE
Use guaranteed binary and source compatibility between releases of Scalafmt

### PR DESCRIPTION
**Pull request by joan38**
Fix for https://github.com/diffplug/spotless/issues/252

### CODE REVIEW

**Comment by nedtwigg** [comment]
Looks like the change breaks older versions of scalafmt?

**Comment by joan38** [comment]
This drops the support for scalafmt < v0.7.0-RC1

**Comment by joan38** [comment]
I tried to run the tests with `gradle test` but it doesn't seem to be the why to do and the CONTRIBUTING.md doesn't specify how to do...

**Comment by nedtwigg** [comment]
Great!  All it needs now is updated CHANGES.md:

- [ ] a summary of the change
- [ ] a link to the newly created PR

If your change only affects a build plugin, and not the lib, then you only need to update the CHANGES.md for that plugin.

If your change affects lib in an end-user-visible way (fixing a bug, updating a version) then you need to update CHANGES.md for both the lib and the build plugins. Users of a build plugin shouldn't have to refer to lib to see changes that affect them.

**Comment by nedtwigg** [comment]
bump

**Pull request merged**
