### PR TITLE
update default KtLint to 0.35.0

### PR DESCRIPTION
**Pull request by agebhar1**

### CODE REVIEW

**Comment by nedtwigg** [comment]
> Unable to resolve dependencies: Failure to find com.pinterest:ktlint:jar:0.35.0 in https://maven-central.storage-download.googleapis.com/repos/central/data/

Thanks for PR, lemme know when ktlint 0.35.0 is live on mavencentral and I'll merge :)

**Comment by agebhar1** [comment]
strange behaviour @nedtwigg - it's available on [Maven Central](https://search.maven.org/artifact/com.pinterest/ktlint/0.35.0/jar) but missing also here https://mvnrepository.com/artifact/com.pinterest.ktlint/ktlint-core ...

**Comment by nedtwigg** [comment]
I just kicked-off a fresh build, and it failed again.  You can replicate on your box with `./gradlew check`.

Maven had a rough couple days at the end of last week: https://status.maven.org/

Screen Shot 2019-10-14 at 9 38 34 AM

Maybe `0.35.0` is stuck in limbo.  People can use it in their builds now by setting the version manually, but I won't change the default until CI passes.

**Comment by agebhar1** [comment]
Really strange. On my box I (Maven) can fetch the artifact from Googles Maven Central Mirror:

**Comment by nedtwigg** [comment]
Reran the build, looks like the 0.35.0 finally propagated out

**Comment by agebhar1** [comment]
Nice, thanks!

**Comment by nedtwigg** [comment]
Released in `x.26.0`

**Pull request merged**
