### PR TITLE
Adds a 'addXmlDeclaration' step to add missing xml declarations

### PR DESCRIPTION
**Pull request by kingargyle**
This adds a Xml Step to add a missing xml declaration to a xml file.  If the xml declaration is there it will not change the file.  If the xml declaration is missing it will add an XML 1.0 declaration.

### CODE REVIEW

**Comment by nedtwigg** [comment]
Thanks for PR!  I think core already has a few ways to accomplish this.  Untested, but here's the gist:

licenseHeader can do this by detecting the first tag by matching the regex `<[^\s\d][^\s]*>`, and then prepending the xml header like so:

```gradle
  licenseHeader('<?xml version="1.0" encoding="UTF-8"?>', '<[^\\s\\d][^\\s]*>')
```

you could also implement the step with a lambda using a [custom step](https://github.com/diffplug/spotless/blob/master/plugin-gradle/README.md#custom-rules).

**Comment by kingargyle** [comment]
Thanks I'll take a look at the licenseHeader.   Do you have better examples of custom step implementations?

**Comment by nedtwigg** [comment]
https://github.com/diffplug/spotless/blob/d1c0c5d5db117282cdc0d107bee2d0bcebe1afa6/PADDEDCELL.md#a-misbehaving-step

https://github.com/diffplug/spotless/blob/d1c0c5d5db117282cdc0d107bee2d0bcebe1afa6/gradle/spotless.gradle#L3-L19

**Comment by kingargyle** [comment]
Was able to use the custom option for gradle to get the xml declaration added.  Thanks.

**Comment by nedtwigg** [comment]
`licenseHeader` didn't work?  Just realized it might need to be:

```
<[^\\s\\d][^\\s]*>      <- what I said
<[^\\?\\s\\d][^\\s]*>   <- what maybe needs to be
```

the advantage of `licenseHeader` is that it will always just work with up-to-date checks, buildcache, etc.  custom steps don't work without `bumpThisNumberIfACustomStepChanges`, which is error-prone.

**Comment by kingargyle** [comment]
@nedtwigg I didn't use it because for a couple of reasons

1. the name of the method is misleading for what is happening.  We aren't adding a licenseHeader but an xml declaration tag.  Two different semantic things.

2.  Needed to learn how to make the custom steps work anyways, so I could show the team locally that we can extend easily Spotless without necessarily having to write Kotlin or Java code and fork the project.

If there was a way to add custom steps, as part of a buildSrc addition or something that might be better.  I know that ktlint allows you to contribute your own custom rules using a mechanism by adding the rules as a depdencency that gets added to the class path.   For now the custom rule is working for our needs.

**Comment by nedtwigg** [comment]
You can use builSrc, and add a step like so: https://github.com/diffplug/spotless/blob/master/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L293

**Pull request closed without merging**
