### PR TITLE
Happy New 2023

### PR DESCRIPTION
**Pull request by davidburstrom**

### CODE REVIEW

**Comment by davidburstrom** [comment]
@nedtwigg I prefer to keep PRs on topic, vis-a-vis #1432 .

**Comment by nedtwigg** [comment]
I love the spirit, but I think your `origin/main` is out of date, causing too many headers to get udpated. I'll cleanup #1432 and merge it shortly :)

**Comment by davidburstrom** [comment]
> I think your origin/main is out of date, causing too many headers to get udpated

That is correct, origin/main was out of date, but it doesn't seem correct that that ref should be used to determine what has changed. I never update my origin/main as part of my workflow, because (usually) there's no point to it. I do use upstream tracking branches, in this case upstream/main, and I think Spotless should determine changed files based on that instead.

**Comment by nedtwigg** [comment]
- https://github.com/diffplug/spotless/issues/1238

**Comment by davidburstrom** [comment]
That looks like it, yes :)

**Pull request closed without merging**
