### PR TITLE
Add header links in changelogs

### PR DESCRIPTION
**Pull request by Goooler**
Follow up #2196.

image

### CODE REVIEW

**Comment by Goooler** [comment]
@nedtwigg I guess this should be finished from `com.diffplug.spotless-changelog` side. A bug or a new feature?

**Comment by nedtwigg** [comment]
What functionality do these Changelog things have that this URL does not?

- https://github.com/diffplug/spotless/releases

My view is that CHANGELOG.md should be as simple as possible, and other tools like e.g. GitHub releases can make it "richer", but I don't think we need to pull that complexity into the changelog itself.

**Comment by Goooler** [comment]
These links point to the releases on GitHub Web, if we don't need them, should keep the formats like `## 3.0.0.BETA2 - 2024-08-25` instead of `#[3.0.0.BETA2] - 2024-08-25`.

**Comment by nedtwigg** [comment]
I'm following this convention: https://keepachangelog.com/en/1.1.0/

**Comment by Goooler** [comment]
Yeah, I noticed. But header links are used in this convention for displaying links in titles and keep the format concise, like this:

image

We don't have these links, therefore `[]` looks redundant. But anyway, such a small thing.

**Pull request closed without merging**
